-- SỮA HẠT: chạy toàn bộ trong Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users on delete cascade, full_name text, role text not null default 'staff' check(role in('owner','staff')), created_at timestamptz default now());
create table if not exists public.materials(id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, supplier text not null, unit text not null, created_by uuid references auth.users, created_at timestamptz default now(), unique(lower(name),lower(supplier)));
create sequence if not exists public.material_code_seq start 1;
create or replace function public.set_material_code() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.code is null or btrim(new.code)='' then new.code='NPL'||lpad(nextval('material_code_seq')::text,4,'0'); end if; return new; end $$;
drop trigger if exists trg_material_code on public.materials; create trigger trg_material_code before insert on public.materials for each row execute function public.set_material_code();
create table if not exists public.receipt_lots(id uuid primary key default gen_random_uuid(), material_id uuid not null references public.materials, lot_no text not null, received_date date not null, expiry_date date, unit_price numeric(18,2) not null check(unit_price>=0), received_qty numeric(18,3) not null check(received_qty>0), remaining_qty numeric(18,3) not null check(remaining_qty>=0), created_by uuid references auth.users, created_at timestamptz default now(), unique(material_id,lot_no));
create table if not exists public.issues(id uuid primary key default gen_random_uuid(), issue_date date not null, batch_name text not null, product_name text not null, status text not null default 'draft' check(status in('draft','posted','cancelled')), revision int not null default 1, created_by uuid references auth.users, posted_at timestamptz, cancelled_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.issue_lines(id uuid primary key default gen_random_uuid(), issue_id uuid not null references public.issues on delete cascade, material_id uuid not null references public.materials, quantity numeric(18,3) not null check(quantity>0), unit_price numeric(18,2) not null default 0, line_total numeric(18,2) generated always as (quantity*unit_price) stored);
create table if not exists public.stock_allocations(id uuid primary key default gen_random_uuid(), issue_line_id uuid not null references public.issue_lines on delete cascade, lot_id uuid not null references public.receipt_lots, quantity numeric(18,3) not null check(quantity>0), unit_price numeric(18,2) not null, unique(issue_line_id,lot_id));
create index if not exists idx_lots_fefo on public.receipt_lots(material_id,expiry_date,received_date) where remaining_qty>0;

create or replace function public.post_issue(p_issue_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare ln record; lt record; need numeric; take_qty numeric; weighted numeric; begin
 if not exists(select 1 from issues where id=p_issue_id and created_by=auth.uid() and status='draft' for update) then raise exception 'Phiếu không hợp lệ hoặc không còn ở trạng thái nháp'; end if;
 for ln in select * from issue_lines where issue_id=p_issue_id loop need:=ln.quantity; weighted:=0;
  for lt in select * from receipt_lots where material_id=ln.material_id and remaining_qty>0 order by expiry_date asc nulls last,received_date,id for update loop
   take_qty:=least(need,lt.remaining_qty); update receipt_lots set remaining_qty=remaining_qty-take_qty where id=lt.id; insert into stock_allocations(issue_line_id,lot_id,quantity,unit_price) values(ln.id,lt.id,take_qty,lt.unit_price); weighted:=weighted+take_qty*lt.unit_price; need:=need-take_qty; exit when need=0;
  end loop; if need>0 then raise exception 'Không đủ tồn kho cho nguyên liệu %',ln.material_id; end if; update issue_lines set unit_price=weighted/ln.quantity where id=ln.id;
 end loop; update issues set status='posted',posted_at=now(),updated_at=now() where id=p_issue_id; end $$;
create or replace function public.reverse_issue(p_issue_id uuid,p_cancel boolean default false) returns void language plpgsql security definer set search_path=public as $$
declare a record; begin if not exists(select 1 from issues where id=p_issue_id and created_by=auth.uid() and status='posted' for update) then raise exception 'Chỉ có thể đảo phiếu đã ghi nhận của chính bạn'; end if;
 for a in select * from stock_allocations where issue_line_id in(select id from issue_lines where issue_id=p_issue_id) for update loop update receipt_lots set remaining_qty=remaining_qty+a.quantity where id=a.lot_id; end loop;
 delete from stock_allocations where issue_line_id in(select id from issue_lines where issue_id=p_issue_id); update issues set status=case when p_cancel then 'cancelled' else 'draft' end,cancelled_at=case when p_cancel then now() else null end,posted_at=null,revision=revision+1,updated_at=now() where id=p_issue_id; end $$;
revoke all on function public.post_issue(uuid) from public; revoke all on function public.reverse_issue(uuid,boolean) from public; grant execute on function public.post_issue(uuid),public.reverse_issue(uuid,boolean) to authenticated;

alter table profiles enable row level security; alter table materials enable row level security; alter table receipt_lots enable row level security; alter table issues enable row level security; alter table issue_lines enable row level security; alter table stock_allocations enable row level security;
create policy "authenticated read profiles" on profiles for select to authenticated using(true); create policy "own profile" on profiles for update to authenticated using(id=auth.uid());
create policy "authenticated materials" on materials for select to authenticated using(true); create policy "insert materials" on materials for insert to authenticated with check(created_by=auth.uid()); create policy "update materials" on materials for update to authenticated using(true);
create policy "authenticated lots" on receipt_lots for select to authenticated using(true); create policy "insert lots" on receipt_lots for insert to authenticated with check(created_by=auth.uid()); create policy "update lots" on receipt_lots for update to authenticated using(true);
create policy "read issues" on issues for select to authenticated using(true); create policy "own issue insert" on issues for insert to authenticated with check(created_by=auth.uid()); create policy "own draft update" on issues for update to authenticated using(created_by=auth.uid() and status='draft'); create policy "own draft delete" on issues for delete to authenticated using(created_by=auth.uid() and status='draft');
create policy "read lines" on issue_lines for select to authenticated using(true); create policy "write own draft lines" on issue_lines for all to authenticated using(exists(select 1 from issues i where i.id=issue_id and i.created_by=auth.uid() and i.status='draft')) with check(exists(select 1 from issues i where i.id=issue_id and i.created_by=auth.uid() and i.status='draft'));
create policy "read allocations" on stock_allocations for select to authenticated using(true);
